apiVersion: v1
kind: ServiceAccount
metadata:
  name: apache
---
apiVersion: v1
kind: Service
metadata:
  name: apache
  labels:
    app: apache
    service: apache
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8080
  selector:
    app: apache
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
      version: v1
  template:
    metadata:
      labels:
        app: apache
        version: v1
    spec:
      serviceAccountName: apache
      containers:
      - image: docker.io/bluefireleads/apache:latest
        imagePullPolicy: Always
        name: apache
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred

